name: terraform

on:
  push:
  pull_request:
    types: [opened, synchronize]

env:
  TF_VAR_dnsimple_token: ${{ secrets.TF_VAR_dnsimple_token }}
  TF_VAR_dnsimple_account: ${{ secrets.TF_VAR_dnsimple_account }}
  TF_VAR_github_pat: ${{ secrets.TF_VAR_github_pat }}

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: format
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.3.2
        tf_actions_subcommand: fmt
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.3.2
        tf_actions_subcommand: init
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: validate
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.3.2
        tf_actions_subcommand: validate
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ github.token }}

  plan:
    name: check
    runs-on: ubuntu-latest
    needs: check
    steps:
    - uses: actions/checkout@master

    - name: init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.3.2
        tf_actions_subcommand: init
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 1.3.2
        tf_actions_subcommand: plan
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ github.token }}
