name: terraform

on: [push]

jobs:
  plan:
    name: "terraform plan"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: 'format'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.17
        tf_actions_subcommand: 'fmt'

    - name: 'init'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.17
        tf_actions_subcommand: 'init'

    - name: 'validate'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.17
        tf_actions_subcommand: 'validate'

    - name: 'plan'
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.17
        tf_actions_subcommand: 'plan'

