name: terraform

on:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: format
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.17
        tf_actions_subcommand: fmt
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.17
        tf_actions_subcommand: init
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: validate
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.17
        tf_actions_subcommand: validate
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ github.token }}

  apply:
    name: apply
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    needs: check

    steps:
    - uses: actions/checkout@master

    - name: init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.17
        tf_actions_subcommand: init
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.17
        tf_actions_subcommand: apply
      env:
        TF_VAR_dnsimple_token: ${{ secrets.TF_VAR_dnsimple_token }}
        TF_VAR_dnsimple_account: ${{ secrets.TF_VAR_dnsimple_account }}
        GITHUB_TOKEN: ${{ github.token }}

    - name: commit and push
      run: |
        if [[ -n $(git status -s) ]]; then
          git config user.email "me@nathanherald.com" && \
          git config user.name "Nathan Herald" && \
          git commit -am 'terraform apply-ed' && \
          git push
        fi

  plan:
    name: plan
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    needs: check
    steps:
    - uses: actions/checkout@master

    - name: init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.17
        tf_actions_subcommand: init
        tf_actions_comment: true
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: plan
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.17
        tf_actions_subcommand: plan
        tf_actions_comment: true
      env:
        TF_VAR_dnsimple_token: ${{ secrets.TF_VAR_dnsimple_token }}
        TF_VAR_dnsimple_account: ${{ secrets.TF_VAR_dnsimple_account }}
        GITHUB_TOKEN: ${{ github.token }}
